method: bayes
metric:
  name: "val/val_mse"
  goal: minimize

parameters:
  training.batch_size:
    values: [16, 32, 64]
  training.learning_rate:
    distribution: log_uniform
    min: 1e-5
    max: 1e-3
  training.optimizer:
    values: ["adam", "adamw"]
  training.scheduler.type:
    values: ["step", "cosine"]
  training.scheduler.step_size:
    values: [5, 10]
  training.scheduler.gamma:
    values: [0.1, 0.5]
  training.scheduler.t_max:
    values: [50, 100]
