# ───────────────────────────────────────────────────────────────────────────────
# src/config/sweep_template.yaml
# ───────────────────────────────────────────────────────────────────────────────
program: src/train.py


command:
  - python
  - src/train.py
  - --config
  - src/config/config.yaml

  - --experiment_id
  - '1'

  - --run_id
  - '1'
  - --dataset
  - 'TB'

  - --use_wandb
  - --use_tensorboard

entity: prime_lab
project: super-diff-xray
method: bayes

# Which metric to optimize (name must match what train() logs via W&B/TensorBoard)
metric:
  name: avg_loss
  goal: minimize

parameters:
  # ─────────────────────────────────────────────────────────────────────────────
  # 2) Core training hyperparameters (from config.yaml)
  # ─────────────────────────────────────────────────────────────────────────────
  training.learning_rate:
    distribution: log_uniform_values
    min: 1e-5          # config.yaml default is 1e-4 :contentReference[oaicite:1]{index=1}
    max: 1e-3

  training.batch_size:
    values: [8, 16, 32]  # config.yaml has 8 :contentReference[oaicite:2]{index=2}; try doubling/quadrupling

  training.val_batch_size:
    values: [8, 16, 32]  # mirror train-batch-size choices

  training.num_epochs:
    values: [50, 100, 150]  # config.yaml uses 50 :contentReference[oaicite:3]{index=3}

  training.num_timesteps:
    values: [500, 750, 1000]  # config.yaml uses 1000 :contentReference[oaicite:4]{index=4}

  training.augmentation:
    values: ["none", "low", "medium", "high"]  # config.yaml default is "low" :contentReference[oaicite:5]{index=5}

  training.normalization:
    values: ["minmax", "zscore"]  # config.yaml default is "minmax" :contentReference[oaicite:6]{index=6}

  # ─────────────────────────────────────────────────────────────────────────────
  # 3) Optimizer & scheduler settings (from config.yaml)
  # ─────────────────────────────────────────────────────────────────────────────
  training.optimizer:
    values: ["adam", "adamw"]  # config.yaml default is "adamw" :contentReference[oaicite:7]{index=7}

  training.beta1:
    values: [0.5, 0.9]  # config.yaml uses 0.9 :contentReference[oaicite:8]{index=8}

  training.beta2:
    values: [0.9, 0.999]  # config.yaml uses 0.999 :contentReference[oaicite:9]{index=9}

  training.weight_decay:
    values: [0.0, 1e-4, 1e-3]  # config.yaml default is 0.0 :contentReference[oaicite:10]{index=10}

  training.scheduler.type:
    values: ["cosine", "linear"]  # config.yaml default is "cosine" :contentReference[oaicite:11]{index=11}

  training.scheduler.t_max:
    values: [50, 100, 150]  # config.yaml sets t_max to 100 :contentReference[oaicite:12]{index=12}

  training.scheduler.eta_min:
    values: [1e-6, 1e-5]  # config.yaml sets ηₘᵢₙ = 1e-6 :contentReference[oaicite:13]{index=13}

  # ─────────────────────────────────────────────────────────────────────────────
  # 4) EMA, clipping, AMP (from config.yaml)
  # ─────────────────────────────────────────────────────────────────────────────
  training.ema_beta:
    values: [0.9, 0.99, 0.995]  # config.yaml uses 0.995 :contentReference[oaicite:14]{index=14}

  training.grad_clip_norm:
    values: [0.5, 1.0, 2.0]  # config.yaml uses 1.0 :contentReference[oaicite:15]{index=15}

  training.use_amp:
    values: [true, false]  # config.yaml default = true :contentReference[oaicite:16]{index=16}

  # ─────────────────────────────────────────────────────────────────────────────
  # 5) Validation / Early‐stopping (from config.yaml)
  # ─────────────────────────────────────────────────────────────────────────────
  training.use_validation:
    values: [true, false]  # config.yaml default = false :contentReference[oaicite:17]{index=17}

  training.early_stopping_patience:
    values: [5, 10, 20]  # config.yaml default = 10 :contentReference[oaicite:18]{index=18}

  # ─────────────────────────────────────────────────────────────────────────────
  # 6) Observability toggles (from config.yaml)
  # ─────────────────────────────────────────────────────────────────────────────
  observability.save_feature_maps:
    values: [true, false]  # config.yaml default = true :contentReference[oaicite:19]{index=19}

  observability.save_tsne:
    values: [true, false]  # config.yaml default = true :contentReference[oaicite:20]{index=20}

  observability.save_umap:
    values: [true, false]  # config.yaml default = true :contentReference[oaicite:21]{index=21}

  observability.compute_fid:
    values: [true, false]  # config.yaml default = true :contentReference[oaicite:22]{index=22}

  observability.compute_lpips:
    values: [true, false]  # config.yaml default = true :contentReference[oaicite:23]{index=23}

  observability.compute_ssim:
    values: [true, false]  # config.yaml default = true :contentReference[oaicite:24]{index=24}

  observability.log_single_sample:
    values: [true, false]  # config.yaml default = true :contentReference[oaicite:25]{index=25}

  observability.log_batch_grid:
    values: [true, false]  # config.yaml default = true :contentReference[oaicite:26]{index=26}

  observability.wandb_sample_table:
    values: [true, false]  # config.yaml default = true :contentReference[oaicite:27]{index=27}
